### ISSUE TITLE
Exception of type 'CSCore.MmException' was thrown.

### ISSUE THREAD

**Issue by dawidkomorowski** [dawidkomorowski/geisha#217]
Sometimes integration tests fail with error:
```csharp
TearDown : CSCore.MmException : Exception of type 'CSCore.MmException' was thrown.
--TearDown
   at CSCore.SoundOut.WaveOutBuffer.Dispose(Boolean disposing)
   at CSCore.SoundOut.WaveOut.DisposeBuffers()
   at CSCore.SoundOut.WaveOut.CleanupResources()
   at CSCore.SoundOut.WaveOut.Dispose(Boolean disposing)
   at CSCore.SoundOut.WaveOut.Dispose()
   at Geisha.Engine.Audio.CSCore.AudioPlayer.Dispose() in C:\GitRepos\geisha\src\Geisha.Engine.Audio.CSCore\AudioPlayer.cs:line 70
   at Geisha.Engine.Audio.CSCore.CSCoreAudioBackend.Dispose() in C:\GitRepos\geisha\src\Geisha.Engine.Audio.CSCore\CSCoreAudioBackend.cs:line 30
   at Autofac.Core.Disposer.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Container.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Geisha.Engine.IntegrationTests.IntegrationTests`1.TearDown() in C:\GitRepos\geisha\test\Geisha.Engine.IntegrationTests\IntegrationTests.cs:line 52
```

It also sometimes happens when running TestGame.

**Comment by dawidkomorowski** [comment]
In #170 `WasapiOut` was changed to `WaveOut`. But the latter API provided by CSCore turned out to have some random crashes so audio API was reverted back to `WasapiOut`. As tested, the problematic audio clip which revealed issue described in #170 was the only one so far, and converting it to another format (WAV -> MP3) removed the issue. Maybe files with some specific parameters are problematic but using different parameters may resolve the issue. If the problem will come back again then further work on this will be needed. But for now no more work related to audio is in plan.
